TYPE=VIEW
query=select `mugua`.`goods`.`goods_id` AS `goods_id`,`mugua`.`goods`.`cat_id` AS `cat_id`,`mugua`.`goods`.`goods_name` AS `goods_name`,`mugua`.`goods`.`shop_price` AS `shop_price` from `mugua`.`goods` order by `mugua`.`goods`.`cat_id`,`mugua`.`goods`.`shop_price` desc
md5=94676d86d482764e13ad49f511505e65
updatable=0
algorithm=1
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-11-19 06:07:47
create-version=1
source=select goods_id,cat_id,goods_name,shop_price from goods order by cat_id asc,shop_price desc
client_cs_name=gb2312
connection_cl_name=gb2312_chinese_ci
view_body_utf8=select `mugua`.`goods`.`goods_id` AS `goods_id`,`mugua`.`goods`.`cat_id` AS `cat_id`,`mugua`.`goods`.`goods_name` AS `goods_name`,`mugua`.`goods`.`shop_price` AS `shop_price` from `mugua`.`goods` order by `mugua`.`goods`.`cat_id`,`mugua`.`goods`.`shop_price` desc
